---
title: "Weight of Fish"
author: "Madeleine Alseryani"
date: "Spring 2022"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
Fish<-read.csv(file = "Fish.csv")
```

# Predicting Fish Weight


## Perch

```{r}
Perch<- filter(Fish, Species == "Perch")
Perch = subset(Perch, select = -Species)
```



### Best Models

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```

From this Model, we can see that the best two regressor models are the ones which include height and weight. It also has an adjusted R squared value of 0.94 making it the best model.


### Best Two regressor model


## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements